// Web-platform stub for the mobile SQLite database.
//
// The real implementation (db.ts) uses expo-sqlite, whose web worker/wasm graph
// cannot be chunked by the Expo dev web server (Metro serializer "Worker chunk not
// found" assertion). Web builds resolve here instead (Metro prefers *.web.ts): the
// module mirrors db.ts exports via type-only references so expo-sqlite is never in
// the web bundle. Values are benign stubs that mimic an empty/in-memory database so
// the app shell, providers and pre-login screens render (data reads yield empties).
import type { SQLiteDatabase } from 'expo-sqlite';

export type { ItemData, InsertItemData, FilterOptions, DatePeriod, ContactData, InsertContactData, SupplierRow, InsertSupplierData, SupplierPurchase, SupplierPayment, SupplierOrderItem, SupplierOrderRow, SubscriptionData } from './db';

/* A Proxy-backed fake database: every method is a no-op, rows reads return empty */
const mockDb: any = new Proxy({}, {
  get: (_t: any, prop: PropertyKey) => {
    if (prop === 'getFirstSync') return () => null;
    if (prop === 'getAllSync') return () => [];
    if (prop === 'withTransactionSync') return (fn: any) => fn();
    if (typeof prop === 'string' && /^(execSync|runSync|closeSync|deleteDatabaseSync)/.test(prop)) return () => undefined;
    if (typeof prop !== 'string') return undefined;
    return () => undefined;
  },
});

export const getDB = (() => mockDb) as unknown as typeof import('./db')['getDB'];

export const initDB = () => { /* web preview: no local database */ };
export const auditLog = () => { /* web preview: audit trail disabled */ };
export const verifyAuditChain = () => ({ ok: true, count: 0, brokenAt: null });
export const getAuditLogs = () => [];
export const getDemoMode = () => false;
export const setDemoMode = (enabled: boolean) => !!enabled;
export const getAppSetting = (_key: string, fallback: string | null = null) => fallback;
export const setComplianceSetting = () => { /* no-op on web */ };
export const getFeatureFlag = (_key: string, fallback = true) => fallback;
export const setFeatureFlag = () => { /* no-op on web */ };
export const generateShegaCode = () => 'WEB' + Math.random().toString(36).slice(2, 8).toUpperCase();

export const resetDemoDb = [] as unknown as typeof import('./db')['resetDemoDb'];
export const seedDemoData = [] as unknown as typeof import('./db')['seedDemoData'];
export const insertCategory = [] as unknown as typeof import('./db')['insertCategory'];
export const getCategories = [] as unknown as typeof import('./db')['getCategories'];
export const getUserCategories = [] as unknown as typeof import('./db')['getUserCategories'];
export const seedDefaultCategories = [] as unknown as typeof import('./db')['seedDefaultCategories'];
export const getNextItemId = [] as unknown as typeof import('./db')['getNextItemId'];
export const logStockMovement = [] as unknown as typeof import('./db')['logStockMovement'];
export const logItemPriceChanges = [] as unknown as typeof import('./db')['logItemPriceChanges'];
export const getPriceHistory = [] as unknown as typeof import('./db')['getPriceHistory'];
export const insertItem = [] as unknown as typeof import('./db')['insertItem'];
export const getItems = [] as unknown as typeof import('./db')['getItems'];
export const toggleItemActive = [] as unknown as typeof import('./db')['toggleItemActive'];
export const getItemById = {} as unknown as typeof import('./db')['getItemById'];
export const getItemByBarcode = [] as unknown as typeof import('./db')['getItemByBarcode'];
export const getItemBarcodes = [] as unknown as typeof import('./db')['getItemBarcodes'];
export const addItemBarcode = [] as unknown as typeof import('./db')['addItemBarcode'];
export const removeItemBarcode = [] as unknown as typeof import('./db')['removeItemBarcode'];
export const setPrimaryBarcode = [] as unknown as typeof import('./db')['setPrimaryBarcode'];
export const getQuickProducts = [] as unknown as typeof import('./db')['getQuickProducts'];
export const addQuickProduct = [] as unknown as typeof import('./db')['addQuickProduct'];
export const removeQuickProduct = [] as unknown as typeof import('./db')['removeQuickProduct'];
export const reorderQuickProducts = [] as unknown as typeof import('./db')['reorderQuickProducts'];
export const isQuickProduct = false as unknown as typeof import('./db')['isQuickProduct'];
export const getItemsWithRecentPriceChanges = [] as unknown as typeof import('./db')['getItemsWithRecentPriceChanges'];
export const getItemsDueForSupplierCheck = [] as unknown as typeof import('./db')['getItemsDueForSupplierCheck'];
export const getSaleById = {} as unknown as typeof import('./db')['getSaleById'];
export const getSaleWithItemsById = {} as unknown as typeof import('./db')['getSaleWithItemsById'];
export const getFilteredItems = [] as unknown as typeof import('./db')['getFilteredItems'];
export const insertSale = [] as unknown as typeof import('./db')['insertSale'];
export const getSales = [] as unknown as typeof import('./db')['getSales'];
export const getSalesByDateRange = [] as unknown as typeof import('./db')['getSalesByDateRange'];
export const getFilteredSales = [] as unknown as typeof import('./db')['getFilteredSales'];
export const insertAdjustment = [] as unknown as typeof import('./db')['insertAdjustment'];
export const getRecentAdjustments = [] as unknown as typeof import('./db')['getRecentAdjustments'];
export const getFilteredAdjustments = [] as unknown as typeof import('./db')['getFilteredAdjustments'];
export const deleteAdjustment = true as unknown as typeof import('./db')['deleteAdjustment'];
export const updateAdjustment = [] as unknown as typeof import('./db')['updateAdjustment'];
export const getActivityFeed = [] as unknown as typeof import('./db')['getActivityFeed'];
export const getSalesSummary = {} as unknown as typeof import('./db')['getSalesSummary'];
export const getTopSellingItems = [] as unknown as typeof import('./db')['getTopSellingItems'];
export const getSlowMovingItems = [] as unknown as typeof import('./db')['getSlowMovingItems'];
export const getExpiringItems = [] as unknown as typeof import('./db')['getExpiringItems'];
export const getDashboardStats = {} as unknown as typeof import('./db')['getDashboardStats'];
export const getInventorySummary = {} as unknown as typeof import('./db')['getInventorySummary'];
export const getInventoryStats = {} as unknown as typeof import('./db')['getInventoryStats'];
export const getLowStockItems = [] as unknown as typeof import('./db')['getLowStockItems'];
export const getReorderSuggestions = [] as unknown as typeof import('./db')['getReorderSuggestions'];
export const getDebtCustomers = [] as unknown as typeof import('./db')['getDebtCustomers'];
export const getDebtSales = [] as unknown as typeof import('./db')['getDebtSales'];
export const processDebtPayment = [] as unknown as typeof import('./db')['processDebtPayment'];
export const markDebtAsLoss = [] as unknown as typeof import('./db')['markDebtAsLoss'];
export const getDebtSummary = {} as unknown as typeof import('./db')['getDebtSummary'];
export const getCustomerPaymentHistory = [] as unknown as typeof import('./db')['getCustomerPaymentHistory'];
export const settleItemCredit = [] as unknown as typeof import('./db')['settleItemCredit'];
export const getOnCreditItems = [] as unknown as typeof import('./db')['getOnCreditItems'];
export const getSalesChartData = [] as unknown as typeof import('./db')['getSalesChartData'];
export const deleteItem = true as unknown as typeof import('./db')['deleteItem'];
export const deleteSale = true as unknown as typeof import('./db')['deleteSale'];
export const deleteSalesByBatchId = [] as unknown as typeof import('./db')['deleteSalesByBatchId'];
export const getInventoryComparisonStats = 0 as unknown as typeof import('./db')['getInventoryComparisonStats'];
export const getCapitalSummary = {} as unknown as typeof import('./db')['getCapitalSummary'];
export const updateItem = [] as unknown as typeof import('./db')['updateItem'];
export const updateSale = [] as unknown as typeof import('./db')['updateSale'];
export const updateSaleItem = [] as unknown as typeof import('./db')['updateSaleItem'];
export const clearDatabase = [] as unknown as typeof import('./db')['clearDatabase'];
export const getAdjustmentSummary = {} as unknown as typeof import('./db')['getAdjustmentSummary'];
export const getSummaryAnalytics = {} as unknown as typeof import('./db')['getSummaryAnalytics'];
export const getTopHighestValueItems = [] as unknown as typeof import('./db')['getTopHighestValueItems'];
export const getInventoryItemsByPeriod = [] as unknown as typeof import('./db')['getInventoryItemsByPeriod'];
export const getMovingItemsWithFilters = [] as unknown as typeof import('./db')['getMovingItemsWithFilters'];
export const getInStockItems = [] as unknown as typeof import('./db')['getInStockItems'];
export const getItemsFilteredByStockStatus = [] as unknown as typeof import('./db')['getItemsFilteredByStockStatus'];
export const getAdjustmentDashboardMetrics = [] as unknown as typeof import('./db')['getAdjustmentDashboardMetrics'];
export const getSummaryMetricsByDateRange = {} as unknown as typeof import('./db')['getSummaryMetricsByDateRange'];
export const getVatSummaryByDateRange = {} as unknown as typeof import('./db')['getVatSummaryByDateRange'];
export const getDrilldownSummaryByDateRange = {} as unknown as typeof import('./db')['getDrilldownSummaryByDateRange'];
export const getRecordsByPeriod = [] as unknown as typeof import('./db')['getRecordsByPeriod'];
export const getRecentSales = [] as unknown as typeof import('./db')['getRecentSales'];
export const getRecentSalesGrouped = [] as unknown as typeof import('./db')['getRecentSalesGrouped'];
export const getRecentItems = [] as unknown as typeof import('./db')['getRecentItems'];
export const getDateRangeForPeriod = {} as unknown as typeof import('./db')['getDateRangeForPeriod'];
export const getCustomerActivity = [] as unknown as typeof import('./db')['getCustomerActivity'];
export const getPaymentMethodBreakdown = [] as unknown as typeof import('./db')['getPaymentMethodBreakdown'];
export const getPeakSalesHoursByItem = [] as unknown as typeof import('./db')['getPeakSalesHoursByItem'];
export const insertWarehouse = [] as unknown as typeof import('./db')['insertWarehouse'];
export const getWarehouses = [] as unknown as typeof import('./db')['getWarehouses'];
export const getWarehouseById = {} as unknown as typeof import('./db')['getWarehouseById'];
export const updateWarehouse = [] as unknown as typeof import('./db')['updateWarehouse'];
export const deleteWarehouse = true as unknown as typeof import('./db')['deleteWarehouse'];
export const getWarehouseStats = [] as unknown as typeof import('./db')['getWarehouseStats'];
export const processIndividualPayment = [] as unknown as typeof import('./db')['processIndividualPayment'];
export const settleDebt = [] as unknown as typeof import('./db')['settleDebt'];
export const insertContact = [] as unknown as typeof import('./db')['insertContact'];
export const getContacts = [] as unknown as typeof import('./db')['getContacts'];
export const getContactsByCategory = [] as unknown as typeof import('./db')['getContactsByCategory'];
export const searchContacts = [] as unknown as typeof import('./db')['searchContacts'];
export const getContactById = {} as unknown as typeof import('./db')['getContactById'];
export const updateContact = [] as unknown as typeof import('./db')['updateContact'];
export const deleteContact = [] as unknown as typeof import('./db')['deleteContact'];
export const getSuppliers = [] as unknown as typeof import('./db')['getSuppliers'];
export const getSupplierList = [] as unknown as typeof import('./db')['getSupplierList'];
export const getSupplierById = {} as unknown as typeof import('./db')['getSupplierById'];
export const searchSuppliers = [] as unknown as typeof import('./db')['searchSuppliers'];
export const insertSupplier = [] as unknown as typeof import('./db')['insertSupplier'];
export const updateSupplier = [] as unknown as typeof import('./db')['updateSupplier'];
export const deleteSupplier = [] as unknown as typeof import('./db')['deleteSupplier'];
export const getSupplierPurchases = [] as unknown as typeof import('./db')['getSupplierPurchases'];
export const getSupplierProducts = [] as unknown as typeof import('./db')['getSupplierProducts'];
export const getSupplierPayments = [] as unknown as typeof import('./db')['getSupplierPayments'];
export const insertSupplierPayment = [] as unknown as typeof import('./db')['insertSupplierPayment'];
export const insertSupplierOrder = [] as unknown as typeof import('./db')['insertSupplierOrder'];
export const getSupplierOrders = [] as unknown as typeof import('./db')['getSupplierOrders'];
export const deleteSupplierOrder = true as unknown as typeof import('./db')['deleteSupplierOrder'];
export const getItemSuppliers = {} as unknown as typeof import('./db')['getItemSuppliers'];
export const linkItemSupplier = [] as unknown as typeof import('./db')['linkItemSupplier'];
export const unlinkItemSupplier = [] as unknown as typeof import('./db')['unlinkItemSupplier'];
export const getSalesGroupedByDateRange = [] as unknown as typeof import('./db')['getSalesGroupedByDateRange'];
export const getPaidOutstandingSummary = {} as unknown as typeof import('./db')['getPaidOutstandingSummary'];
export const insertPack = [] as unknown as typeof import('./db')['insertPack'];
export const insertPacksBatch = [] as unknown as typeof import('./db')['insertPacksBatch'];
export const insertReturn = [] as unknown as typeof import('./db')['insertReturn'];
export const getReturnsBySaleId = [] as unknown as typeof import('./db')['getReturnsBySaleId'];
export const getReturnStats = {} as unknown as typeof import('./db')['getReturnStats'];
export const processReturn = [] as unknown as typeof import('./db')['processReturn'];
export const getAdjustmentById = {} as unknown as typeof import('./db')['getAdjustmentById'];
export const getComplianceSettings = {} as unknown as typeof import('./db')['getComplianceSettings'];
export const searchInventory = [] as unknown as typeof import('./db')['searchInventory'];
export const insertOrder = [] as unknown as typeof import('./db')['insertOrder'];
export const getOrders = [] as unknown as typeof import('./db')['getOrders'];
export const getOrderSummary = {} as unknown as typeof import('./db')['getOrderSummary'];
export const getOrderById = {} as unknown as typeof import('./db')['getOrderById'];
export const convertOrderToSale = [] as unknown as typeof import('./db')['convertOrderToSale'];
export const convertOrderToDebt = [] as unknown as typeof import('./db')['convertOrderToDebt'];
export const cancelOrder = [] as unknown as typeof import('./db')['cancelOrder'];
export const getLatestItemsByPeriod = [] as unknown as typeof import('./db')['getLatestItemsByPeriod'];
export const updateSubscriptionPlan = true as unknown as typeof import('./db')['updateSubscriptionPlan'];
export const verifySubscriptionPayment = false as unknown as typeof import('./db')['verifySubscriptionPayment'];
export const enablePremiumForTesting = true as unknown as typeof import('./db')['enablePremiumForTesting'];
export const approveSubscription = true as unknown as typeof import('./db')['approveSubscription'];
export const startFreeTrial = true as unknown as typeof import('./db')['startFreeTrial'];
export const syncServerSubscription = [] as unknown as typeof import('./db')['syncServerSubscription'];
export const rejectSubscription = false as unknown as typeof import('./db')['rejectSubscription'];
export const cancelSubscription = true as unknown as typeof import('./db')['cancelSubscription'];
export const expireSubscription = true as unknown as typeof import('./db')['expireSubscription'];
export const renewSubscription = true as unknown as typeof import('./db')['renewSubscription'];
export const confirmRenewal = true as unknown as typeof import('./db')['confirmRenewal'];
export const insertSubscriptionPayment = [] as unknown as typeof import('./db')['insertSubscriptionPayment'];
export const getSubscriptionPayments = [] as unknown as typeof import('./db')['getSubscriptionPayments'];
export const getSubscriptionRenewals = [] as unknown as typeof import('./db')['getSubscriptionRenewals'];
export const getSubscriptionAuditLog = [] as unknown as typeof import('./db')['getSubscriptionAuditLog'];
export const checkAndExpireSubscription = [] as unknown as typeof import('./db')['checkAndExpireSubscription'];
export const isPremiumFeatureUnlocked = false as unknown as typeof import('./db')['isPremiumFeatureUnlocked'];
