import type { TutorialDefinition } from '../types';

export const budgetTutorial: TutorialDefinition = {
  id: 'budget',
  screen: 'budget',
  title: 'Budget Management',
  subtitle: 'Plan and track spending',
  steps: [
    {
      id: 'bud-intro',
      targetId: 'bud-header',
      title: 'Budget Dashboard',
      description: 'Create and manage budgets for your business. Track planned vs actual spending across categories, departments, or projects.',
      tooltipPosition: 'bottom',
      actionType: 'none',
      spotlightPadding: 8,
    },
    {
      id: 'bud-create',
      targetId: 'bud-create-btn',
      title: 'Create a Budget',
      description: 'Tap to create a new budget. Set a name, type (business, department, project), period (monthly, quarterly, yearly), and allocate amounts by category.',
      tooltipPosition: 'left',
      actionType: 'tap',
      waitForAction: true,
      spotlightPadding: 6,
    },
    {
      id: 'bud-overview',
      targetId: 'bud-overview',
      title: 'Budget Overview',
      description: 'See your total budget, spending to date, and remaining balance. The health indicator shows if you\'re on track, near limit, or over budget.',
      tooltipPosition: 'bottom',
      actionType: 'none',
      spotlightPadding: 6,
    },
    {
      id: 'bud-categories',
      targetId: 'bud-categories',
      title: 'Category Breakdown',
      description: 'View spending by category. Each category shows planned vs actual spend. Tap to drill down for detailed analysis.',
      tooltipPosition: 'top',
      actionType: 'none',
      spotlightPadding: 6,
    },
    {
      id: 'bud-trends',
      targetId: 'bud-trends',
      title: 'Monthly Trends',
      description: 'Track your budget performance over time. See monthly trends and forecast future spending based on historical patterns.',
      tooltipPosition: 'top',
      actionType: 'none',
      spotlightPadding: 6,
    },
  ],
};
