import type { TutorialDefinition } from '../types';

export const dashboardTutorial: TutorialDefinition = {
  id: 'dashboard',
  screen: 'dashboard',
  title: 'Dashboard',
  subtitle: 'Master your business at a glance',
  steps: [
    {
      id: 'dash-intro',
      targetId: 'dash-header',
      title: 'Welcome to Your Dashboard',
      description: 'This is your command center. View today\'s revenue, profit, expenses, and sales count at a glance. The dashboard gives you a real-time snapshot of your business health.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'dash-quick-stats',
      targetId: 'dash-stats',
      title: 'Quick Status Cards',
      description: 'At-a-glance status of low stock items, credit customers, and on-credit inventory. Tap any card to open the full list and take action.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'dash-sparkline',
      targetId: 'dash-sparkline',
      title: 'Performance Metrics',
      description: 'Swipe left or right to cycle through today\'s Revenue, Gross Profit, Sales Count, and Expenses. The sparkline compares today against yesterday\'s performance.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
    {
      id: 'dash-search',
      targetId: 'dash-search',
      title: 'Universal Search',
      description: 'Search across all your inventory, sales, expenses, and contacts from one place. Start typing to find anything instantly.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'dash-alerts',
      targetId: 'dash-alerts',
      title: 'Action Alerts',
      description: 'Tap the bell to open your notifications — low stock items, overdue debts, deposits, and other urgent updates that need your attention.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'dash-activity',
      targetId: 'dash-activity',
      title: 'Recent Activity Feed',
      description: 'See a live feed of everything happening in your business — sales, expenses, adjustments, and more. Tap any entry to view details.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
    {
      id: 'dash-health',
      targetId: 'dash-health',
      title: 'Business Health Score',
      description: 'Your overall business health rating based on multiple factors. A higher score means your business is performing well. Tap to see the breakdown.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
    {
      id: 'dash-sidebar',
      targetId: 'dash-avatar',
      title: 'Profile & Navigation',
      description: 'Tap your avatar to open the sidebar menu. From there you can access all sections: Sales, Inventory, Expenses, Settings, and more.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
  ],
};
