import type { TutorialDefinition } from '../types';

export const expenseFormTutorial: TutorialDefinition = {
  id: 'expense-form',
  screen: 'expense-form',
  title: 'Record an Expense',
  subtitle: 'Log a business expense step by step',
  steps: [
    {
      id: 'ef-intro',
      targetId: 'ef-header',
      title: 'Recording an Expense',
      description: 'Follow these steps to log a new expense. Fill in the amount, category, date, and optionally set up recurring payments.',
      tooltipPosition: 'bottom',
      fullContainer: true,
},
    {
      id: 'ef-amount',
      targetId: 'ef-amount',
      title: 'Enter Amount',
      description: 'Type the expense amount. This is the total amount paid or owed for this expense.',
      tooltipPosition: 'bottom',
      exampleValue: '15,000',
    },
    {
      id: 'ef-category',
      targetId: 'ef-category',
      title: 'Select Category',
      description: 'Choose a category that best describes this expense. Categories help you track spending patterns and stay organized.',
      tooltipPosition: 'bottom',
      fullContainer: true,
},
    {
      id: 'ef-date',
      targetId: 'ef-date',
      title: 'Expense Date',
      description: 'Set the date when this expense occurred. This is used for accurate monthly and period reporting.',
      tooltipPosition: 'bottom',
    },
    {
      id: 'ef-description',
      targetId: 'ef-description',
      title: 'Add Description',
      description: 'Add a brief description or note about this expense. Include details like vendor name, purpose, or receipt reference.',
      tooltipPosition: 'bottom',
      exampleValue: 'Office supplies — printer toner & paper',
    },
    {
      id: 'ef-recurring',
      targetId: 'ef-recurring',
      title: 'Recurring Expense',
      description: 'Toggle this on for bills that repeat (rent, utilities, subscriptions). Set the frequency — daily, weekly, monthly, or yearly.',
      tooltipPosition: 'bottom',
    },
    {
      id: 'ef-budget',
      targetId: 'ef-budget',
      title: 'Link to Budget',
      description: 'Optionally link this expense to a budget category. This helps track spending against your planned budget.',
      tooltipPosition: 'bottom',
    },
    {
      id: 'ef-commit',
      targetId: 'ef-commit-btn',
      title: 'Save Expense',
      description: 'Review all details and tap to record the expense. It will appear in your expense ledger and reports immediately.',
      tooltipPosition: 'bottom',
    },
  ],
};
