import type { TutorialDefinition } from '../types';

export const inventoryFormTutorial: TutorialDefinition = {
  id: 'inventory-form',
  screen: 'inventory-form',
  title: 'Add Inventory Item',
  subtitle: 'Add a new product to your stock',
  steps: [
    {
      id: 'if-intro',
      targetId: 'if-header',
      title: 'Adding a New Item',
      description: 'Follow these steps to add a new product to your inventory. You\'ll configure identification, pricing, and classification.',
      tooltipPosition: 'bottom',

      actionType: 'none',
      fullContainer: true,
},
      {
      id: 'if-name',
      targetId: 'if-name',
      title: 'Item Name & Category',
      description: 'Give your item a clear, descriptive name. Select the appropriate category — this helps with organization and reporting.',
      tooltipPosition: 'bottom',
      actionType: 'none',
      exampleValue: 'Premium Roasted Coffee Beans',
    },
    {
      id: 'if-brand',
      targetId: 'if-brand',
      title: 'Manufacturer / Brand',
      description: 'Enter the manufacturer or brand name. This is useful for identifying products, especially when dealing with multiple suppliers.',
      tooltipPosition: 'bottom',
      actionType: 'none',
      exampleValue: 'Ethio Coffee Export PLC',
    },
    {
      id: 'if-unit',
      targetId: 'if-unit',
      title: 'Unit & Quantity',
      description: 'Choose the unit (pieces, kg, litre, meter, etc.) and enter the initial stock quantity. For bulk items, configure box/roll settings.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'if-pricing',
      targetId: 'if-pricing',
      title: 'Cost & Selling Price',
      description: 'Enter the buying price (cost) and selling price. The system calculates your profit margin automatically and warns if you\'re selling at a loss.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'if-supplier',
      targetId: 'if-supplier',
      title: 'Supplier Information',
      description: 'Add supplier details if purchasing on credit. Log the supplier name, phone, account number, and credit terms.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'if-expiry',
      targetId: 'if-expiry',
      title: 'Expiration & Quality',
      description: 'Set an expiration date for perishable items and a quality grade. The system will alert you when items are close to expiring.',
      tooltipPosition: 'bottom',
      actionType: 'none',
      exampleValue: '12/2026',
    },
    {
      id: 'if-commit',
      targetId: 'if-commit-btn',
      title: 'Save to Inventory',
      description: 'Review all details and tap "Initialize Asset" to add the item to your inventory vault. The item will appear in your stock ledger immediately.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
  ],
};
