import type { TutorialDefinition } from '../types';

export const inventoryTutorial: TutorialDefinition = {
  id: 'inventory',
  screen: 'inventory',
  title: 'Inventory',
  subtitle: 'Manage your stock efficiently',
  steps: [
    {
      id: 'inv-intro',
      targetId: 'inv-header',
      title: 'Inventory Vault',
      description: 'Your complete inventory management system. Track stock levels, monitor valuations, and manage every item in your store.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'inv-add',
      targetId: 'inv-add-btn',
      title: 'Add New Item',
      description: 'Tap here to add a new product. Fill in the name, category, quantity, prices, and supplier details. You can also configure box/roll settings for bulk items.',
      tooltipPosition: 'left',
      actionType: 'none',
    },
    {
      id: 'inv-valuation',
      targetId: 'inv-valuation',
      title: 'Portfolio Valuation',
      description: 'See the total value of your inventory. This updates automatically as you add, sell, or adjust items. Track how your stock value changes over time.',
      tooltipPosition: 'bottom',
      actionType: 'none',
    },
    {
      id: 'inv-list',
      targetId: 'inv-list',
      title: 'Stock Ledger',
      description: 'All your inventory items listed here. Use the search bar to find items, filter by category, or sort by price, quantity, or name.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
    {
      id: 'inv-item',
      targetId: 'inv-item-card',
      title: 'Item Cards',
      description: 'Each card shows the item name, current stock, selling price, and unit. Items below threshold are flagged. Tap a card to view or edit details.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
    {
      id: 'inv-stats',
      targetId: 'inv-stats',
      title: 'Inventory Insights',
      description: 'View stock distribution by category, see low-stock alerts, track fast vs slow-moving items, and monitor expiration dates.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
    {
      id: 'inv-restock',
      targetId: 'inv-restock-btn',
      title: 'Restock Items',
      description: 'When stock runs low, tap to open the product order modal. Select items and set order quantities to replenish your inventory.',
      tooltipPosition: 'top',
      actionType: 'none',
    },
  ],
};
