import type { TutorialDefinition } from '../types';

export const salesHubTutorial: TutorialDefinition = {
  id: 'sales-hub',
  screen: 'sales-hub',
  title: 'Sales Hub',
  subtitle: 'Track and manage your sales',
  steps: [
    {
      id: 'sales-intro',
      targetId: 'sales-header',
      title: 'Sales Hub Overview',
      description: 'This is your complete sales management center. View total revenue, track transactions, analyze trends, and record new sales — all in one place.',
      tooltipPosition: 'bottom',
      actionType: 'none',

      spotlightPadding: 8,
      fullContainer: true,
},
      {
      id: 'sales-revenue',
      targetId: 'sales-revenue',
      title: 'Revenue Summary',
      description: 'Your total sales revenue for today. The bar chart below shows your weekly trend so you can spot patterns at a glance.',
      tooltipPosition: 'bottom',
      actionType: 'none',
      spotlightPadding: 6,
    },
    {
      id: 'sales-add',
      targetId: 'sales-add-btn',
      title: 'Record a New Sale',
      description: 'Tap the + button to expand the action menu, then tap the add item icon to start recording a new sale.',
      tooltipPosition: 'left',
      actionType: 'none',
      spotlightPadding: 20,
    },
    {
      id: 'sales-ledger',
      targetId: 'sales-ledger',
      title: 'Sales Ledger',
      description: 'Every transaction is recorded here. Scroll through your sales history, tap any entry to see details, edit, or delete.',
      tooltipPosition: 'top',
      actionType: 'none',
      spotlightPadding: 6,
    },
    {
      id: 'sales-chart',
      targetId: 'sales-chart',
      title: 'Sales Analytics Chart',
      description: 'Visualize your sales trends with interactive charts. Toggle between daily, weekly, and monthly views to analyze performance over time.',
      tooltipPosition: 'top',
      actionType: 'none',
      spotlightPadding: 6,
    },
    {
      id: 'sales-top',
      targetId: 'sales-top-items',
      title: 'Top Performing Items',
      description: 'See which products sell the most. Use this insight to stock popular items and maximize your revenue.',
      tooltipPosition: 'top',
      actionType: 'none',
      spotlightPadding: 6,
    },
    {
      id: 'sales-pending',
      targetId: 'sales-pending',
      title: 'Pending & Credit Sales',
      description: 'Manage unsettled credit sales here. Track who owes you money, send reminders, and mark payments as received.',
      tooltipPosition: 'top',
      actionType: 'none',
      spotlightPadding: 6,
    },
  ],
};
